[package]
name = 'satay-zap'
version = '1.0.0'

[addresses]
satay_zap = "0xa063aa74aeb7aac297161df445de42d99e2e9ac0d560af9500b2db29f2b8c4d6"

[dependencies.satay]
git = 'https://github.com/satay-protocol/satay-aptos'
rev = 'main'

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap'
rev = 'v0.4.3'
subdir = './liquidswap_router_v2'